[SES-1732] Fix multiple link previews
oxen-io/session-android pull request #1463
Opened 2024-04-17 06:07 UTC by bemusementpark

tracked internally: https://optf.atlassian.net/browse/SES-1732

Getting a loading animation bug when trying to send a link with a preview attached but the loading animation doesn’t go away and the link preview doesn’t work at first, take a couple of tries to get preview to load

2024-04-17 06:39 UTC, AL-Session requested changes
Once we get the `https://` prefix entered into a message then every single character added after that briefly flashes up a link preview view before removing it, which looks a bit jank.

Is there any way we can check whether this is something valid we can preview rather than adding and then removing the view?

2024-04-17 07:09 UTC, KeeJef commented
> Once we get the `https://` prefix entered into a message then every single character added after that briefly flashes up a link preview view before removing it, which looks a bit jank.
> 
> Is there any way we can check whether this is something valid we can preview rather than adding and then removing the view?

Can we wait for the TLD to be entered?

2024-04-17 07:20 UTC, AL-Session commented
> > Once we get the `https://` prefix entered into a message then every single character added after that briefly flashes up a link preview view before removing it, which looks a bit jank.
> > Is there any way we can check whether this is something valid we can preview rather than adding and then removing the view?
> 
> Can we wait for the TLD to be entered?

Potentially - or perhaps because URLs can't contain spaces only check for link previews when the last entered character is space, and thenn also not remove then re-add on other instances of space if the last found link preview is the same as the existing one.

2024-04-18 00:07 UTC, bemusementpark commented
I'll create another ticket for that issue.

2024-04-18 00:25 UTC, AL-Session approved these changes
Approved. New ticket will be created to improve the preview view display by preventing it add / remove on each keypress.

2024-04-24 02:18 UTC, merged